language: csharp
solution: Everlook.sln
sudo: required
dist: trusty
before_install:
    - sudo apt-get install mono-complete libgtk3.0-cil
    - nuget restore lib/liblistfile/libwarcraft
    - nuget restore lib/liblistfile
