version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Release
install:
    - ps: git config --global url."https://github.com/".insteadOf "git@github.com:"
before_build:
  - git submodule update --init --recursive
  - dotnet restore Everlook.sln
platform: x86
build:
  parallel: true
  project: Everlook.sln
  verbosity: quiet
after_test:
  - bash <(curl -s https://codecov.io/bash)
