version: 1.0.{build}
configuration:
  - Release
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
  - curl -fsS -o gtk-sharp-3.msi http://gemmei.acc.umu.se/pub/GNOME/binaries/win32/gtk-sharp/2.99/gtk-sharp-2.99.3.msi
  - msiexec /i C:\projects\everlook\gtk-sharp-3.msi /qn
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - git submodule update --init --recursive
platform: x86
build:
  parallel: true
  project: Everlook.sln
  verbosity: quiet
after_test:
  - bash <(curl -s https://codecov.io/bash)
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
