version: 1.0.{build}
image: Visual Studio 2017
configuration:
  - Release
install:
    - ps: git config --global url."https://github.com/".insteadOf "git@github.com:"
before_build:
  - curl -fsS -o gtk-sharp-3.msi http://gemmei.acc.umu.se/pub/GNOME/binaries/win32/gtk-sharp/2.99/gtk-sharp-2.99.3.msi
  - msiexec /i C:\projects\everlook\gtk-sharp-3.msi /qn
  - git submodule update --init --recursive
  - nuget restore Everlook.sln
platform: x86
build:
  parallel: true
  project: Everlook.sln
  verbosity: quiet
after_test:
  - bash <(curl -s https://codecov.io/bash)
